<?php

use Zilker\MailerCode\ViewModel\Product\MailerCode;
use Zilker\MailerCodeApi\Api\Data\MailerCodeInterface;
/**
 * @var MailerCode $viewModel;
 */
$viewModel = $block->getMailerCodeSessionViewModel();
/**
* @var MailerCodeInterface $mailerCode
 */
$mailerCode=$viewModel->getSessionData();
?>
<?php if ($mailerCode) : ?>
<h3>MailerCode Applied</h3>
    <p><strong>Code: </strong><?= $mailerCode->getSearchAltCode() ?></p>
    <p><h2>Offer Price: $<?= $mailerCode->getPrice()?> (Min Quantity: <?= $mailerCode->getMinQuantity() ?>)</h2></p>
<?php endif; ?>