<?php

use Zilker\MailerCode\ViewModel\Product\MailerCode;
use Zilker\MailerCodeApi\Api\Data\MailerCodeInterface;

/**
     * @var MailerCode $mailerCodeViewModel
     */
    $mailerCodeViewModel = $block->getMailerCodeViewModel();
    /**
     * @var MailerCodeInterface $mailerCode;
     */
    $mailerCode = $mailerCodeViewModel->getSessionData();
?>
<?php if ($mailerCode): ?>
    <h3>MailerCode Applied</h3>
    <h3><strong>Code: </strong><?=$mailerCode->getSearchAltCode()?></h3>
    <h2>Offer Price: <?=$mailerCode->getPrice()?> (Min Quantity: <?=$mailerCode->getMinQuantity()?>)</h2>
<?php endif; ?>